var dataSrc = [
    {
        "book_id": "54",
        "title": "Xenophon's imperial fiction : on the education of Cyrus",        
        "author": "James Tatum",        
        "ISBN": "0691067570",        
        "publicationdate": "1989",        
        "entry_date": "Aug 21, 2005",        
        "rating": 3,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/06/05/0605bc3262615b3597a41414141414141414141.jpg",
        "tags": [
            "greek history",
            "barbarians",
            "persia",
            "ancient novel"
        ],        
    },
    {
        "book_id": "133",
        "title": "Witchcraft at Salem",        
        "author": "Chadwick Hansen",        
        "ISBN": "0807611379",        
        "publicationdate": "1969",        
        "entry_date": "Aug 22, 2005",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0807611379.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "witchcraft",
            "magic",
            "american history",
            "history"
        ],        
    },
    {
        "book_id": "141",
        "title": "The world of classical myth : gods and goddesses, heroines and heroes",        
        "author": "Carl A. P. Ruck",        
        "ISBN": "0890895759",        
        "publicationdate": "1994",        
        "entry_date": "Aug 22, 2005",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/06/05/0605bc3262615b3597a41414141414141414141.jpg",
        "tags": [
            "greek mythology",
            "mythology",
            "myth"
        ],        
    },
    {
        "book_id": "460",
        "title": "You are here : personal geographies and other maps of the imagination",        
        "author": "Katharine A. Harmon",        
        "ISBN": "1568984308",        
        "publicationdate": "2004",        
        "entry_date": "Jun 15, 2008",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/1568984308.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "maps",
            "design"
        ],        
    },
    {
        "book_id": "465",
        "title": "You just don't understand : women and men in conversation",        
        "author": "Deborah Tannen",        
        "ISBN": "0345372050",        
        "publicationdate": "1990",        
        "entry_date": "Jun 15, 2008",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0345372050.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "psychology",
            "linguistics",
            "relationships"
        ],        
    },
    {
        "book_id": "574",
        "title": "The world of Odysseus [by] M.I. Finley",        
        "author": "M. I. Finley",        
        "ISBN": "014013686X",        
        "publicationdate": "1965",        
        "entry_date": "Aug 30, 2005",        
        "rating": 4.5,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/014013686X.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "homer",
            "ancient greece",
            "bronze age"
        ],        
    },
    {
        "book_id": "590",
        "title": "Women and law in classical Greece",        
        "author": "Raphael Sealey",        
        "ISBN": "0807842621",        
        "publicationdate": "1990",        
        "entry_date": "Aug 30, 2005",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0807842621.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "women",
            "greek law"
        ],        
    },
    {
        "book_id": "23332",
        "title": "Xenophon ... with an English translation ..",        
        "author": "Xenophon",        
        "ISBN": "",        
        "publicationdate": "pigdog",        
        "entry_date": "Sep 9, 2005",        
        "rating": 0,
        "language": "grc",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/06/05/0605bc3262615b3597a41414141414141414141.jpg",
        "tags": [
            "lcl",
            "loeb classical library",
            "greek",
            "translations"
        ],        
    },
    {
        "book_id": "23516",
        "title": "Wrath of God: The days of the Antichrist",        
        "author": "Livio Fanzaga",        
        "ISBN": "0912141824",        
        "publicationdate": "1998",        
        "entry_date": "Sep 9, 2005",        
        "rating": 0.5,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/e7/46/e74668bfaf6f53d596f48346977414141414141.jpg",
        "tags": [
            "religion",
            "catholicism"
        ],        
    },
    {
        "book_id": "23558",
        "title": "Women in scripture : a dictionary of named and unnamed women in the Hebrew Bible, the",        
        "author": "Carol L. Meyers",        
        "ISBN": "0395709369",        
        "publicationdate": "2000",        
        "entry_date": "Sep 9, 2005",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0395709369.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "bible",
            "women",
            "hebrew bible",
            "nt"
        ],        
    },
    {
        "book_id": "41389",
        "title": "XML for dummies",        
        "author": "Ed Tittel",        
        "ISBN": "0764506927",        
        "publicationdate": "2000",        
        "entry_date": "Sep 12, 2005",        
        "rating": 2,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0764506927.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "xml",
            "librarything",
            "dummies",
            "for dummies"
        ]
    },
    {
        "book_id": "2651411",
        "title": "World of wonders",        
        "author": "Robertson Davies",        
        "ISBN": "014016796X",        
        "publicationdate": "1975",        
        "entry_date": "Apr 18, 2006",        
        "rating": 5,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/014016796X.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "Not started"
        ],        
    },
    {
        "book_id": "3589685",
        "title": "Your Safari Dragons: In Search of the Real Komodo Dragon",        
        "author": "Daniel White",        
        "ISBN": "1595940146",        
        "publicationdate": "2005",        
        "entry_date": "Jun 14, 2006",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/1595940146.01._SCLZZZZZZZ_.jpg",
        "tags": [
            null
        ],        
    },
    {
        "book_id": "4007938",
        "title": "Wings of madness : Alberto Santos-Dumont and the invention of flight",        
        "author": "Paul Hoffman",        
        "ISBN": "0786866594",        
        "publicationdate": "2003",        
        "entry_date": "Jul 1, 2006",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0786866594.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "flight",
            "history",
            "france",
            "paris"
        ],        
    },
    {
        "book_id": "6598863",
        "title": "Women, Fire, and Dangerous Things",        
        "author": "George Lakoff",        
        "ISBN": "0226468046",        
        "publicationdate": "1990",        
        "entry_date": "Sep 13, 2006",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0226468046.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "wishlist"
        ]
    },
    {
        "book_id": "30966619",
        "title": "Zeus: A Journey Through Greece in the Footsteps of a God",        
        "author": "Tom Stone",        
        "ISBN": "158234518X",        
        "publicationdate": "2008",        
        "entry_date": "Jun 15, 2008",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/158234518X.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "wishlist",
            "greek religion"
        ]        
    },
    {
        "book_id": "33808474",
        "title": "Women in Science: Time to Recognize the Obvious",        
        "author": "Ismail Serageldin",        
        "ISBN": "9776163483",        
        "publicationdate": "2006",        
        "entry_date": "Jul 26, 2008",        
        "rating": 0,
        "language": "",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/af/d4/afd45bb85a8e8cf593143315977414141414141.jpg",
        "tags": [
            "Bibliotheca Alexandrina",
            "wikimania2008"
        ],        
    },
    {
        "book_id": "34469906",
        "title": "The Wisdom of Crowds",        
        "author": "James Surowiecki",        
        "ISBN": "0385721706",        
        "publicationdate": "2005",        
        "entry_date": "Aug 9, 2008",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0385721706.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "sociology",
            "social software",
            "librarything"
        ]
    },
    {
        "book_id": "39285978",
        "title": "Zona disagio",        
        "author": "Jonathan Franzen",        
        "ISBN": "8806193112",        
        "publicationdate": "Fri, 01 Aug 2008 00:00:00 0000",        
        "entry_date": "Dec 16, 2008",        
        "rating": 0,
        "language": "",                                        
        "cover": "http://ecx.images-amazon.com/images/P/8806193112.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "41601804",
        "title": "Zarafa: a giraffe's true story, from deep in Africa to the heart of Paris",        
        "author": "Michael Allin",        
        "ISBN": "0802713394",        
        "publicationdate": "1998",        
        "entry_date": "Feb 11, 2009",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0802713394.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "44474477",
        "title": "World War Z : an oral history of the zombie war",        
        "author": "Max Brooks",        
        "ISBN": "0307346609",        
        "publicationdate": "2006",        
        "entry_date": "Apr 24, 2009",        
        "rating": 2.5,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/0c/43/0c43b9ee495c0a4593843475467414141414141.jpg",
        "tags": [
            "zombies",
            "oral history",
            "apple"
        ]        
    },
    {
        "book_id": "47747605",
        "title": "You Can Work Any Hundred Hours a Week You Want (In Your Underwear)!!: The History of Microcosm Publishing as Told to the Best of My Recollection",        
        "author": "Joe Biel",        
        "ISBN": "",        
        "publicationdate": "2006",        
        "entry_date": "Jul 14, 2009",        
        "rating": 0,
        "language": "",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/0c/ab/0cab3e11336067e593053535641414141414141.jpg",
        "tags": [
            "diy",
            "zines",
            "librarything",
            "quimby's"
        ]
    },
    {
        "book_id": "47747682",
        "title": "Xerography Debt #25",        
        "author": "Davida Gypsy Breier",        
        "ISBN": "",        
        "publicationdate": "April 2009",        
        "entry_date": "Jul 14, 2009",        
        "rating": 0,
        "language": "",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/81/16/811681434dc2f73593061535641414141414141.jpg",
        "tags": [
            "zines",
            "quimby's"
        ]        
    },
    {
        "book_id": "47750641",
        "title": "Wit and the writing of history : the rhetoric of historiography in imperial Rome",        
        "author": "Paul Plass",        
        "ISBN": "0299118045",        
        "publicationdate": "1988",        
        "entry_date": "Jul 14, 2009",        
        "rating": 2,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0299118045.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "roman literature",
            "roman history",
            "historiography"
        ]        
    },
    {
        "book_id": "48255337",
        "title": "World War Z: An Oral History of the Zombie War",        
        "author": "Max Brooks",        
        "ISBN": "0307346617",        
        "publicationdate": "2007",        
        "entry_date": "Jul 25, 2009",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0307346617.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "48255667",
        "title": "World War Hulk",        
        "author": "Greg Pak",        
        "ISBN": "0785126708",        
        "publicationdate": "2009",        
        "entry_date": "Jul 25, 2009",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0785126708.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "48256176",
        "title": "World War I (DK Eyewitness Books)",        
        "author": "Simon Adams",        
        "ISBN": "075663007X",        
        "publicationdate": "2007",        
        "entry_date": "Jul 25, 2009",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/075663007X.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "48398966",
        "title": "Xero: Turn-of-the-Millenia (Zero)",        
        "author": "La Ruocco",        
        "ISBN": "0974345407",        
        "publicationdate": "2003",        
        "entry_date": "Jul 27, 2009",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0974345407.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "48398969",
        "title": "Xero #9 January 1998",        
        "author": "Priest",        
        "ISBN": "",        
        "publicationdate": "1998",        
        "entry_date": "Jul 27, 2009",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/de/5b/de5beef9b5ceff2597959414141414141414141.jpg",        
    },
    {
        "book_id": "48398974",
        "title": "Xero #9 January 1998",        
        "author": "Priest",        
        "ISBN": "",        
        "publicationdate": "1998",        
        "entry_date": "Jul 27, 2009",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/de/5b/de5beef9b5ceff2597959414141414141414141.jpg",        
    },
    {
        "book_id": "56067578",
        "title": "You Are Not a Gadget: A Manifesto",        
        "author": "Jaron Lanier",        
        "ISBN": "0307269647",        
        "publicationdate": "2010",        
        "entry_date": "Jan 31, 2010",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0307269647.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "audiobook",
            "wrong edition"
        ]      
    },
    {
        "book_id": "60623884",
        "title": "The World's Greatest Book of Useless Information: If You Thought You Knew All the Things You Didn't Need to Know - Think Again",        
        "author": "Noel Botham",        
        "ISBN": "",        
        "publicationdate": "1995",        
        "entry_date": "Jun 1, 2010",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/de/5b/de5beef9b5ceff2597959414141414141414141.jpg",        
    },
    {
        "book_id": "62624305",
        "title": "Wild things",        
        "author": "",        
        "ISBN": "",        
        "publicationdate": "?",        
        "entry_date": "Jul 25, 2010",        
        "rating": 0,
        "language": "und",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/de/5b/de5beef9b5ceff2597959414141414141414141.jpg",        
    },
    {
        "book_id": "73540459",
        "title": "Winston's War: Churchill, 1940-1945",        
        "author": "Max Hastings",        
        "ISBN": "030726839X",        
        "publicationdate": "2010",        
        "entry_date": "May 20, 2011",        
        "rating": 5,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/030726839X.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "churchill",
            "war",
            "wwii",
            "britain"
        ]        
    },
    {
        "book_id": "74851780",
        "title": "The Worship of the Early Church",        
        "author": "Ferdinand Hahn",        
        "ISBN": "0800601270",        
        "publicationdate": "1973",        
        "entry_date": "Jun 23, 2011",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/ab/56/ab561d40cee2bcd596f6c336751414141414141.jpg",
        "tags": [
            "early church",
            "religion",
            "christianity",
            "nt"
        ],        
    },
    {
        "book_id": "79141967",
        "title": "Ysabel",        
        "author": "Guy Gavriel Kay",        
        "ISBN": "0143016695",        
        "publicationdate": "2007",        
        "entry_date": "Oct 18, 2011",        
        "rating": 0,
        "language": "",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0143016695.01._SCLZZZZZZZ_.jpg"
    },
    {
        "book_id": "87533306",
        "title": "Wulfsyarn",        
        "author": "Phillip Mann",        
        "ISBN": "0575047674",        
        "publicationdate": "1990",        
        "entry_date": "Jul 10, 2012",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/1f/bc/1fbc71a8802dc96592f75765151414141414141.jpg"
    },
    {
        "book_id": "91840037",
        "title": "Wool",        
        "author": "Hugh Howey",        
        "ISBN": "1461057205",        
        "publicationdate": "2011",        
        "entry_date": "Nov 24, 2012",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/1461057205.01._SCLZZZZZZZ_.jpg"
    },
    {
        "book_id": "97656733",
        "title": "The World's Greatest Short Stories (Dover Thrift Editions)",        
        "author": "James Daley",        
        "ISBN": "0486447162",        
        "publicationdate": "2006",        
        "entry_date": "Apr 28, 2013",        
        "rating": 4,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0486447162.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "99803099",
        "title": "Wool",        
        "author": "Hugh Howey",        
        "ISBN": "9781476733951",        
        "publicationdate": "2013",        
        "entry_date": "Jul 9, 2013",        
        "rating": 2,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/1476733953.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "science fiction",
            "fiction"
        ]
    },
    {
        "book_id": "103193471",
        "title": "Without Their Permission: How the 21st Century Will Be Made, Not Managed",        
        "author": "Alexis Ohanian",        
        "ISBN": "1455520020",        
        "publicationdate": "2013",        
        "entry_date": "Oct 26, 2013",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/1455520020.01._SCLZZZZZZZ_.jpg"
    },
    {
        "book_id": "112381841",
        "title": "A Wizard of Earthsea: The Earthsea Cycle, Book 1",        
        "author": "Ursula K. Le Guin",        
        "ISBN": "",        
        "publicationdate": "2009",        
        "entry_date": "Sep 9, 2014",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/72/1e/721ef76779f7f54596d4d666a51414141414141.jpg"
    },
    {
        "book_id": "112618928",
        "title": "Ἡροδότου Ἁλικαρνησσέος ἱστορίης ἀπόδεξις",        
        "author": "Ἡρόδοτος",        
        "ISBN": "",        
        "publicationdate": "?",        
        "entry_date": "Sep 18, 2014",        
        "rating": 0,
        "language": "",                                        
        "cover": "http://pics.cdn.librarything.com/picsizes/de/5b/de5beef9b5ceff2597959414141414141414141.jpg",
        "tags": [
            "greek history",
            "love",
            "greek literature",
            "blank cover"
        ]
    },
    {
        "book_id": "114265576",
        "title": "The Wonderful Flight to the Mushroom Planet",        
        "author": "Eleanor Cameron",        
        "ISBN": "0316125407",        
        "publicationdate": "1988",        
        "entry_date": "Nov 24, 2014",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0316125407.01._SCLZZZZZZZ_.jpg"
    },
    {        
        "book_id": "118889688",
        "title": "Young Frankenstein",        
        "author": "Gene Wilder",        
        "ISBN": "",        
        "publicationdate": "2006",        
        "entry_date": "Jun 3, 2015",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/B000G6BLWE.01._SCLZZZZZZZ_.jpg",
        "tags": [
            "bettercover"
        ],
    },
    {        
        "book_id": "119874072",
        "title": "Wuthering Heights (Tantor Unabridged Classics)",        
        "author": "Emily Bronte",        
        "ISBN": "1400156882",        
        "publicationdate": "2008",        
        "entry_date": "Jul 10, 2015",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/1400156882.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "124471069",
        "title": "Zeus : a journey through Greece in the footsteps of a god",        
        "author": "Tom Stone",        
        "ISBN": "9781582345185",        
        "publicationdate": "2008",        
        "entry_date": "Dec 24, 2015",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/158234518X.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "131387846",
        "title": "Young Catholic America : emerging adults in, out of, and gone from the church",        
        "author": "Christian Smith",        
        "ISBN": "9780199341078",        
        "publicationdate": "2014",        
        "entry_date": "Jun 19, 2016",        
        "rating": 0,
        "language": "eng",                                        
        "cover": "http://ecx.images-amazon.com/images/P/0199341079.01._SCLZZZZZZZ_.jpg",        
    },
    {
        "book_id": "131542739",
        "title": "Would You Baptize an Extraterrestrial?: .... and Other Questions from the Astronomers' In-box at the Vatican Observatory",        
        "author": "Guy Consolmagno",        
        "ISBN": "",        
        "publicationdate": "2014",        
        "entry_date": "Jun 23, 2016",        
        "rating": 3.5,
        "language": "",                                        
        "cover": "http://ecx.images-amazon.com/images/I/51yNOE%2BKYZL._SCLZZZZZZZ_.jpg",
        "tags": [
            "science",
            "religion",
            "catholicism",
            "jesuits in space"
        ]
    }
]